[features]
seeds = false
skip-lint = false

[programs.devnet]
todo_list_app = "318eTzYaWmAS95mXySjXwnZJ1YPpkJ5Z7T9rMEytMVzX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
